### ISSUE TITLE
Schema uploading is not working properly

### ISSUE THREAD

**Issue by joni3k** [alma-cdk/openapix#15]
Simply uploading the generated schema to s3 as an Asset and importing it later is not enough, when x-amazon integrations are generated:
1. CDK generates references to AWS resources as Tokens
2. The generated references are set to the generated spec-file as Tokens, and exported as is to S3
3. The Tokens are resolved during deploy normally, but because we import the specfile with those Tokens unresolved the deployment fails

A possible solution could utilize custom resources, or lifecycle hooks

**Comment by aripalo** [comment]
Based on initial research it seems that we may be able to fix this by using:
```ts
Stack.of(scope).resolve(obj)
```

… which essentially resolves CDK tokens into CloudFormation references & intrinsic functions.
