### ISSUE TITLE
Resources defined outside of OpenApi spec disappears from API Gateway

### ISSUE THREAD

**Issue by haapti** [alma-cdk/openapix#43]
**What im trying to do**

```js
const api = new openapix.Api(this, 'ExampleApi', {
  source: path.join(__dirname, '../example-schema.yaml'),
  paths: {
    '/add': {
      get: new openapix.LambdaIntegration(this, addFn),
    },
  },
});

api.root
      .addResource("_hiddenResource")
      .addMethod("GET", new LambdaIntegration(hiddenFn));
```

**The issue**

Running `cdk deploy` on first time everything is ok and i can see the resources defined outside of OpenApi spec in API Gateway. Running `cdk deploy` on second time and thereafter these resources disappear from API Gateway although the resources are still in place in CloudFormation template.

**Comment by aripalo** [comment]
Hmm this needs some investigation, but my gut feeling is that this is a feature that maybe impossible to support. Or at least I'm not really confident that this will work even with standard CloudFormation (i.e. defining the API Gateway with both OpenAPI schema together with explicit resources).

Looking at [CDK docs on `SpecRestApi`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway.SpecRestApi.html) (which this construct is based on):
> All Resources and Methods need to be defined as part of the OpenAPI specification file, and cannot be added via the CDK.

So based on that and the fact that I feel this some kind of corner case, I'm thinking of closing this as "wont fix".

But also I'm interested on the use case for this. The philosophy of this construct is exactly that you define the whole API with OpenAPI schema. Is your use case something that you want to have a "hidden" API paths/methods that are not documented externally? If so, I would probably approach this in the following way:
- Define everything in OpenAPI schema
- Use openapix to define the API Gateway
- Use some existing tooling or build a script that removes these "hidden" paths from the external documentation that you're distributing to stakeholders

**Comment by haapti** [comment]
yeah, good point @aripalo 

on my usage case i have cloudfront on front of my api route service and i felt that it is easier to handle some of cloudfront behaviors in api route (hook up lambda functions).

cloudfront setup goes roughly like this:

```
<cloudfront>/*.mp3 -> <apigateway>/api/_redirect // response with statusCode 302
<cloudfront>/api -> <apigateway>/api
```

this said, better option might be just spin up a second api route service in same stack for these "extra" stuff outside of the spec
