### ISSUE TITLE
Is this project still being developed?

### ISSUE THREAD

**Issue by wojtekgalaj** [alma-cdk/openapix#58]
I really like the ideas here. I don't have the capacity to take ownership of it currently so I'd like to know if this is still live since the last commit is pretty old?

Thanks.

**Comment by mpiltz** [comment]
> I really like the ideas here. I don't have the capacity to take ownership of it currently so I'd like to know if this is still live since the last commit is pretty old?
> 
> Thanks.

Hi,

Yes, it is still developed, but due to multiple reasons, we haven't had the time to work on this recently.

**Comment by wojtekgalaj** [comment]
Amazing, I'll keep an eye on the repo in that case. Thank you <3
